import Head from 'next/head'
import { Inter } from 'next/font/google'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faArrowRight, faArrowLeft } from '@fortawesome/free-solid-svg-icons';
import { useDispatch, useSelector } from 'react-redux';
import ProductCard from '@/components/ProductCard';
import Accordion from '@/components/AccordionCard';
import { goToPrevious } from '@/features/carousel/carouselSlice';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { productItems, basket } = useSelector((store) => store.product)
  const { slides, currentIndex } = useSelector((store) => store.carousel)
  const { accordionData } = useSelector((store) => store.accordion)
  const dispatch = useDispatch();
  const notify = () => toast.success('Ürün Sepete Eklendi', {
    position: "top-right",
    autoClose: 1500,
    hideProgressBar: false,
    closeOnClick: true,
    pauseOnHover: true,
    draggable: true,
    progress: undefined,
    theme: "light",
  });


  return (
    <>
      <Head>
        <title>afterpay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ToastContainer />
        <div className='container w-full relative'>
          {/* Slider */}
          <div className='flex lg:justify-between justify-center mt-5 lg:mt-0'>
            <div onClick={() => dispatch(goToPrevious())} className='lg:w-16 lg:h-24 lg:absolute lg:-left-20 lg:top-48 slider-button rounded-md flex justify-center items-center hover:cursor-pointer'><FontAwesomeIcon icon={faArrowLeft} className='icon text-white' /></div>
            <div onClick={() => dispatch(goToPrevious())} className='lg:w-16 lg:h-24 lg:absolute lg:-right-20 lg:top-48 slider-button rounded-md flex justify-center items-center hover:cursor-pointer'><FontAwesomeIcon icon={faArrowRight} className='icon text-white' /></div>
          </div>
          <div className='w-3/4 mx-auto lg:w-full h-full lg:h-96 bg-gray-300 mt-11 rounded-md flex justify-center items-center'>
            {/* <p className='text-2xl'>Slider</p> */}
            <img alt='slider' className='w-full h-full rounded-md' src={slides[currentIndex].url} />
          </div>

          {/* Deals Of The Week */}
          <div className='w-ful flex justify-between items-center mt-20'>
            <h2 className='opportunities-title text-2xl lg:text-[32px]'>Haftanın Fırsatları</h2>
            <div className='flex'>
              <button className='w-11 h-11 bg-afterpay-orange flex justify-center items-center mr-4'><FontAwesomeIcon icon={faArrowLeft} className='w-4 text-white' /></button>
              <button className='w-11 h-11 bg-afterpay-lightgray flex justify-center items-center'><FontAwesomeIcon icon={faArrowRight} className='w-4 text-black' /></button>
            </div>
          </div>
          <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 md:w-full w-1/2 mx-auto gap-y-5 md:gap-y-0 md:gap-x-11 mt-14'>
            {productItems.filter(item => item.opportunityWeek === true).map(filteredItem => (
              <ProductCard key={filteredItem.id} filteredItem={filteredItem} notify={notify} />
            ))}
          </div>

          {/* Highlights */}
          <div className='w-ful flex justify-between items-center mt-20'>
            <h2 className='opportunities-title text-2xl md:text-[32px]'>Öne Çıkanlar</h2>
            <div className='flex'>
              <button className='font-bold font-[18px] flex items-center'>Tüm Öne Çıkanlar <FontAwesomeIcon icon={faArrowRight} className='w-4 h-3 ml-1' /></button>
            </div>
          </div>
          <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 w-full gap-x-11 gap-y-12 mt-14'>
            {productItems.map(filteredItem => (
              <ProductCard key={filteredItem.id} filteredItem={filteredItem} notify={notify} />
            ))}
          </div>

          {/* Frequently Asked Questions */}
          <h2 className='text-center text-3xl lg:text-4xl mt-44'>Sıkça Sorulan Sorular</h2>
          <p className='text-center w-full lg:w-[630px] mx-auto mt-7 text-gray-500 text-md'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed orci sapien, malesuada sollicitudin mi vel, tristique eleifend metus. </p>
          <div className='w-full flex flex-col items-center mt-[72px] px-4 lg:px-0'>
            {
              accordionData.map((item, index) => (
                <Accordion key={index} item={item} index={index} />
              ))
            }
          </div>
        </div>
      </main>
    </>
  )
}
